import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import {parse, compileScript, compileTemplate} from '@vue/compiler-sfc';

test('RTGS dialog retains failed submissions, blocks submission during upload, and closes its own dialog', async () => {
  const {descriptor} = parse(fs.readFileSync(new URL('../app/components/annualprocurementplans/submitPayment.vue', import.meta.url), 'utf8'));
  assert.deepEqual(compileTemplate({source: descriptor.template.content, filename: 'submitPayment.vue', id: 'rtgs'}).errors, []);
  const code = `import {ref, computed} from '${import.meta.resolve('vue')}';
    export const requests = [];
    export let succeeds = false;
    export const allowSuccess = () => {succeeds = true;};
    const useAnnualprocurementplanStore = () => ({submitInvoiceRtgs: async (...args) => {requests.push(args); return succeeds;}});
    const useDocmanUpload = () => ({uploadFile: async () => {throw new Error('Offline');}});
    ${compileScript(descriptor, {id: 'rtgs'}).content}`;
  const module = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
  const state = module.default.setup({planUuid: 'plan-one'}, {expose() {}});
  const other = module.default.setup({planUuid: 'plan-two'}, {expose() {}});
  const opened = [], closed = [];
  state.paymentDialog.value = {showModal: () => opened.push('one'), close: () => closed.push('one')};
  other.paymentDialog.value = {showModal: () => opened.push('two'), close: () => closed.push('two')};
  other.openModal();
  assert.deepEqual(opened, ['two']);
  Object.assign(state.form.value, {source_bank: 'Bank', account_name: 'Entity', account_number: '00123', source_reference: 'REF-1', proof_key: 'proof', file_name: 'proof.pdf'});
  state.uploading.value = true;
  await state.submit();
  state.closeModal();
  assert.equal(module.requests.length, 0);
  assert.deepEqual(closed, []);
  state.uploading.value = false;
  await state.submit();
  assert.match(state.error.value, /could not be submitted/);
  assert.equal(state.form.value.proof_key, 'proof');
  assert.equal(state.submitting.value, false);
  await state.onProofChange({target: {files: [{name: 'replacement.pdf'}], value: 'file'}});
  assert.match(state.error.value, /Unable to upload/);
  assert.equal(state.uploading.value, false);
  module.allowSuccess();
  await state.submit();
  assert.deepEqual(closed, ['one']);
  assert.equal(module.requests[1][0], 'plan-one');
  assert.equal(module.requests[1][1].account_number, '00123');
});
