<template>
  <div class="w-full space-y-6 p-4 sm:p-6">
    <header class="card border border-base-200 bg-base-100 shadow-sm"><div class="card-body gap-3 p-5">
      <div class="breadcrumbs text-sm"><ul><li><NuxtLink to="/evaluations">My Evaluations</NuxtLink></li><li>Least Cost Selection</li><li>{{ evaluation?.tender?.reference || 'Workspace' }}</li></ul></div>
      <div class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-xl font-bold">{{ evaluation?.tender?.title || 'LCS evaluation' }}</h1><p class="font-mono text-xs text-base-content/50">{{ evaluation?.tender?.reference }}</p></div><div class="flex flex-wrap items-center gap-2"><button v-if="workspace?.minutes_url" class="btn btn-outline btn-sm" @click="openMinutes"><Icon name="lucide:file-text" class="h-4 w-4" />View committee minutes</button><button v-if="canViewCommitteeEvaluations" class="btn btn-outline btn-sm" @click="openCommitteeEvaluations"><Icon name="lucide:clipboard-list" class="h-4 w-4" />View committee evaluations</button><span v-if="evaluation" class="badge badge-lg badge-info">{{ humanize(evaluation.status) }}</span></div></div>
    </div></header>

    <div v-if="loading" class="flex items-center gap-2 rounded-2xl border border-base-200 bg-base-100 p-8"><span class="loading loading-spinner loading-sm" />Loading evaluation workspace…</div>
    <div v-else-if="notInitialized" class="rounded-2xl border border-dashed border-primary/40 bg-primary/5 p-10 text-center"><Icon name="lucide:users" class="mx-auto h-10 w-10 text-primary" /><h2 class="mt-3 text-lg font-semibold">Evaluation committee not appointed</h2><p class="mx-auto mt-2 max-w-xl text-sm text-base-content/60">Open the tender details and appoint the committee before starting evaluation.</p><NuxtLink :to="`/tenders/${tenderUuid}?tab=evaluation-committee`" class="btn btn-primary mt-5">Open tender details</NuxtLink></div>
    <div v-else-if="errorMessage && !workspace" class="alert alert-error"><Icon name="lucide:triangle-alert" class="h-5 w-5" />{{ errorMessage }}</div>

    <template v-else-if="workspace">
      <div v-if="message" class="alert" :class="messageOk ? 'alert-success' : 'alert-error'"><Icon :name="messageOk ? 'lucide:circle-check' : 'lucide:triangle-alert'" class="h-5 w-5" />{{ message }}</div>

      <ul class="steps steps-vertical w-full text-xs lg:steps-horizontal">
        <li v-for="stage in stages" :key="stage.key" class="step" :class="stage.done ? 'step-primary' : ''">{{ stage.label }}</li>
      </ul>

      <section v-if="evaluation.status === 'COMMITTEE_SETUP'" class="alert alert-info"><Icon name="lucide:users" class="h-5 w-5" /><div class="flex-1"><p class="font-semibold">Committee appointment is not complete</p><p class="text-sm">An authorised tender manager must finish appointing the evaluation committee.</p></div><NuxtLink v-if="canEdit" :to="`/tenders/${tenderUuid}?tab=evaluation-committee`" class="btn btn-sm">Manage committee</NuxtLink></section>

      <section v-if="evaluation.status === 'COMMITTEE_APPOINTED'" class="rounded-xl border border-primary/25 bg-primary/5 p-4">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <div class="flex items-start gap-3"><Icon name="lucide:circle-check-big" class="mt-0.5 h-5 w-5 text-primary" /><div><p class="font-semibold">The evaluation committee is ready</p><p class="text-sm text-base-content/60">{{ canReview ? 'Start the evaluation to release bidder responses to the appointed voting members.' : 'Waiting for an authorised evaluation officer to start the evaluation.' }}</p></div></div>
          <button v-if="canReview" class="btn btn-primary btn-sm" :disabled="saving" @click="startEvaluation"><span v-if="saving" class="loading loading-spinner loading-sm" /><Icon v-else name="lucide:play" class="h-4 w-4" />Start Evaluation</button>
        </div>
      </section>

      <LcsChairShortlist v-if="showShortlist && workspace.actors.is_chairperson && evaluation.status === 'CHAIR_REVIEW'" :tender-uuid="tenderUuid" :workspace="workspace" @back="showShortlist = false" @submitted="handleShortlistSubmitted" />

      <section v-else-if="!['COMMITTEE_SETUP', 'COMMITTEE_APPOINTED'].includes(evaluation.status)">
        <main class="space-y-5">
          <div v-if="workspace.actors.is_voting_member && ['INDIVIDUAL_EVALUATION', 'CHAIR_REVIEW'].includes(evaluation.status)" class="card border border-warning/40 bg-warning/5 shadow-sm"><div class="card-body gap-3 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-semibold">Local evaluation draft</h2><p class="text-sm text-base-content/60">{{ completedDraftCount }} of {{ workspace.bids.length }} bidder decisions completed. Changes are saved on this device as you work.</p></div><button class="btn btn-primary" :disabled="saving || !hasLocalDrafts || !allDecisionsComplete" @click="commitEvaluation"><span v-if="saving" class="loading loading-spinner loading-sm" /><Icon v-else name="lucide:cloud-upload" class="h-4 w-4" />Commit evaluation</button></div><div v-if="hasLocalDrafts" class="alert alert-warning py-2"><Icon name="lucide:triangle-alert" class="h-5 w-5" /><span><strong>This evaluation has not yet been committed.</strong> Your draft is stored locally and will remain available after an outage or browser restart on this device.</span></div><p v-else class="text-xs text-success">All displayed decisions match the committed server record.</p></div></div>
          <div v-if="workspace.actors.is_chairperson && !workspace.configuration.demo_mode" class="alert alert-info"><Icon name="lucide:lock-keyhole" class="h-5 w-5" /><div><p class="font-semibold">Step 2 is locked for the chairperson</p><p class="text-sm">The chairperson has no voting rights in production. Once all voting members commit their evaluations, the shortlisting action becomes available.</p></div></div>
          <div class="card border border-base-200 bg-base-100 shadow-sm"><div class="card-body gap-4 p-5"><div><h2 class="font-semibold">Responding bidders</h2><p class="text-sm text-base-content/55">Each voting committee member records a compliance decision. Bid documents open inside this workspace.</p></div>
            <article v-for="bid in workspace.bids" :key="bid.uuid" class="rounded-xl border border-base-200 p-4">
              <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-semibold">{{ bid.bidder?.name }}</h3><p class="text-xs text-base-content/50">{{ bid.committee_completed }} of {{ bid.committee_size }} committee decisions complete · {{ bid.document_count }} attached document{{ bid.document_count === 1 ? '' : 's' }}</p></div><div class="flex gap-2"><span v-if="bid.unanimously_compliant" class="badge badge-success">Compliant</span><button class="btn btn-outline btn-xs" @click="openEligibility(bid)"><Icon name="lucide:eye" class="h-4 w-4" />View and evaluate documents</button></div></div>
              <div class="mt-3 rounded-lg bg-base-200/50 p-3"><div class="flex flex-wrap items-center gap-2"><span class="badge badge-sm badge-outline">{{ bid.evaluation_scope?.response_rules }}</span><span class="text-xs text-base-content/55">{{ bid.evaluation_scope?.response_rules === 'ALL ITEMS' ? 'Evaluate every item in each responded lot' : 'Evaluate only selected and responded items' }}</span></div><div v-for="lot in bid.evaluation_scope?.lots || []" :key="lot.id" class="mt-2 text-xs"><span class="font-medium">{{ lot.description }}:</span> {{ lot.products.map(product => product.description).join(', ') || 'No responded items' }}</div></div>
              <div v-if="workspace.actors.is_voting_member && ['INDIVIDUAL_EVALUATION', 'CHAIR_REVIEW'].includes(evaluation.status)" class="mt-4 grid gap-3">
                <select v-model="decisionForms[bid.uuid].compliant" class="select select-bordered w-full" required><option :value="null" disabled>Select decision</option><option :value="true">Compliant</option><option :value="false">Not compliant</option></select>
                <textarea v-model.trim="decisionForms[bid.uuid].comments" class="textarea textarea-bordered min-h-24 w-full" placeholder="Evaluation comments" /><p class="text-right text-xs text-base-content/45"><Icon name="lucide:hard-drive" class="mr-1 inline h-3.5 w-3.5" />Saved locally</p>
              </div>
            </article>
          </div></div>

          <div v-if="workspace.actors.is_chairperson && evaluation.status === 'CHAIR_REVIEW'" class="card border border-primary/30 bg-primary/5 shadow-sm"><div class="card-body gap-4 p-5"><div><h2 class="font-semibold">Committee evaluation complete</h2><p class="text-sm text-base-content/55">Review every committee member's responses before proceeding to step 3 shortlisting.</p></div><div><button class="btn btn-primary" @click="openShortlist"><Icon name="lucide:list-checks" class="h-4 w-4" />Proceed to shortlist</button></div></div></div>

          <div v-if="workspace.actors.is_pmu_member && evaluation.status === 'PMU_REVIEW'" class="card border border-info/30 bg-base-100 shadow-sm"><div class="card-body gap-4 p-5"><div><h2 class="font-semibold">PMU financial review</h2><p class="text-sm text-base-content/55">Confirm the scoped least-cost recommendations before forwarding them to the Accounting Officer, or return them to the chairperson for correction.</p></div><LcsFinancialReview :review="workspace.financial_review" /><LcsCommentsThread v-if="workspace.comments_thread?.length" :comments="workspace.comments_thread" /><textarea v-model.trim="pmuComments" class="textarea textarea-bordered min-h-28" placeholder="PMU review comments" /><div class="flex flex-wrap gap-2"><button class="btn btn-outline btn-warning" :disabled="saving || !pmuComments" @click="returnToChair"><Icon name="lucide:undo-2" class="h-4 w-4" />Send back to chairperson</button><button class="btn btn-info" :disabled="saving || !pmuComments" @click="submitPmu">Send to Accounting Officer</button></div></div></div>

          <div v-if="workspace.actors.is_accounting_officer && evaluation.status === 'ACCOUNTING_OFFICER_REVIEW'" class="card border border-warning/30 bg-base-100 shadow-sm"><div class="card-body gap-4 p-5"><div><h2 class="font-semibold">Accounting Officer financial review and decision</h2><p class="text-sm text-base-content/55">Review the scoped financial recommendations. The available action follows the tender's SPOC route and evaluated award threshold.</p></div><LcsFinancialReview :review="workspace.financial_review" /><LcsCommentsThread v-if="workspace.comments_thread?.length" :comments="workspace.comments_thread" /><div v-if="requiresSpoc" class="alert alert-warning"><Icon name="lucide:landmark" class="h-5 w-5" /><div><p class="font-semibold">SPOC review is mandatory</p><p class="text-sm">This tender is subject to SPOC review and cannot be approved directly.</p></div></div><textarea v-model.trim="aoComments" class="textarea textarea-bordered min-h-24" placeholder="Decision comments" /><div class="flex flex-wrap gap-2"><button class="btn btn-outline btn-warning" :disabled="saving || !aoComments" @click="returnToPmu"><Icon name="lucide:undo-2" class="h-4 w-4" />Send back to PMU</button><button v-if="!requiresSpoc" class="btn btn-success" :disabled="saving" @click="submitAo('APPROVE')"><Icon name="lucide:badge-check" class="h-4 w-4" />Approve recommendation and award</button><button v-else class="btn btn-warning" :disabled="saving" @click="submitAo('SUBMIT_SPOC')"><Icon name="lucide:send" class="h-4 w-4" />Send for SPOC</button></div></div></div>

          <div v-if="evaluation.status === 'SPOC_FEE_PENDING'" class="alert alert-warning"><Icon name="lucide:receipt-text" class="h-5 w-5" /><div><p class="font-semibold">SPOC fees awaiting payment</p><p class="text-sm">{{ workspace.spoc_fees.paid }} of {{ workspace.spoc_fees.total }} participating bidders have paid. Due {{ formatDate(workspace.spoc_fees.due_at) }}.</p></div></div>
          <div v-if="evaluation.status === 'SPOC_REVIEW'" class="alert alert-info"><Icon name="lucide:landmark" class="h-5 w-5" />The recommendation is ready for SPOC review.</div>
          <div v-if="evaluation.status === 'APPROVED'" class="alert alert-success"><Icon name="lucide:award" class="h-5 w-5" />The Accounting Officer approved the least-cost award recommendation.</div>
        </main>

      </section>
    </template>

    <dialog ref="committeeEvaluationDialog" class="modal">
      <div class="modal-box flex h-[92vh] w-11/12 max-w-7xl flex-col p-0">
        <div class="flex items-center justify-between border-b border-base-200 p-4"><div><h2 class="font-semibold">Committee evaluations</h2><p class="text-xs text-base-content/50">All committed decisions, comments, and bidder eligibility information.</p></div><button class="btn btn-circle btn-ghost btn-sm" @click="committeeEvaluationDialog?.close()"><Icon name="lucide:x" /></button></div>
        <div v-if="committeeEvaluationsLoading" class="flex flex-1 items-center justify-center gap-2"><span class="loading loading-spinner loading-sm" />Loading committee evaluations…</div>
        <div v-else class="flex-1 space-y-4 overflow-y-auto p-5">
          <article v-for="member in committeeEvaluations" :key="member.uuid" class="overflow-hidden rounded-xl border border-base-200">
            <div class="flex flex-wrap items-center justify-between gap-2 border-b border-base-200 bg-base-200/40 px-4 py-3"><div><h3 class="font-semibold">{{ member.name }}</h3><p class="text-xs text-base-content/45">{{ member.email }}</p></div><div class="flex items-center gap-2"><span v-if="member.is_chairperson" class="badge badge-primary badge-sm">Chairperson</span><span class="badge badge-outline badge-sm">{{ member.completed_bids }} responses</span></div></div>
            <div class="overflow-x-auto"><table class="table table-sm"><thead><tr><th>Bidder</th><th>Decision</th><th>Evaluation comments</th><th>Committed</th><th></th></tr></thead><tbody><tr v-for="response in member.responses" :key="response.bid_uuid"><td class="font-medium">{{ response.bidder?.name }}</td><td><span class="badge badge-sm" :class="response.compliant ? 'badge-success' : 'badge-error'">{{ response.compliant ? 'Compliant' : 'Not compliant' }}</span></td><td class="max-w-xl whitespace-pre-wrap">{{ response.comments || '—' }}</td><td class="text-xs">{{ formatDateTime(response.completed_at) }}</td><td class="text-right"><button class="btn btn-outline btn-xs whitespace-nowrap" @click="openEvaluationEligibility(response)"><Icon name="lucide:clipboard-check" class="h-4 w-4" />View eligibility</button></td></tr><tr v-if="!member.responses.length"><td colspan="5" class="py-6 text-center text-base-content/45">No voting responses were submitted by this member.</td></tr></tbody></table></div>
          </article>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop"><button>close</button></form>
    </dialog>

    <dialog ref="documentDialog" class="modal">
      <div class="modal-box flex flex-col p-0" :class="reviewMode === 'eligibility' ? 'h-screen max-h-none w-screen max-w-none rounded-none' : 'h-[92vh] w-11/12 max-w-7xl'">
        <div class="flex items-center justify-between border-b border-base-200 p-4"><div><h2 class="font-semibold">{{ documentBid?.bidder?.name }} — {{ reviewMode === 'eligibility' ? 'eligibility review' : 'committee minutes' }}</h2><p class="text-xs text-base-content/50">Answers and attachments are displayed inside the evaluation workspace.</p></div><button class="btn btn-circle btn-ghost btn-sm" @click="closeDocuments"><Icon name="lucide:x" /></button></div>
        <div class="grid min-h-0 flex-1 lg:grid-cols-[minmax(420px,1fr)_minmax(420px,1fr)]">
          <div class="overflow-y-auto border-r border-base-200 p-4">
            <template v-if="reviewMode === 'eligibility'">
              <section class="mb-6 rounded-lg border border-info/30 bg-info/5 p-3"><div class="flex items-center gap-2"><span class="badge badge-info badge-sm">{{ eligibilityReview.scope?.response_rules }}</span><p class="text-sm font-medium">Evaluation scope</p></div><div v-for="lot in eligibilityReview.scope?.lots || []" :key="lot.id" class="mt-2 text-xs"><p class="font-medium">{{ lot.description }}</p><p class="text-base-content/60">{{ lot.products.map(product => product.description).join(', ') || 'No responded items' }}</p></div></section>
              <section class="space-y-2"><h3 class="font-semibold">Eligibility responses</h3><article v-for="row in eligibilityReview.eligibility" :key="row.uuid" class="rounded-lg border border-base-200 p-3"><p class="text-xs text-base-content/45">{{ row.group }}</p><p class="mt-1 text-sm font-medium">{{ row.question }}</p><div class="mt-2 flex items-center justify-between gap-2"><span class="badge" :class="row.file && !row.answer ? 'badge-info' : 'badge-outline'">{{ displayResponse(row) }}</span><button v-if="row.file" class="btn btn-outline btn-xs" @click="activeDocument = row.file">View attachment</button></div></article><p v-if="!eligibilityReview.eligibility.length" class="text-sm text-base-content/45">No eligibility questions configured.</p></section>
              <section class="mt-6 space-y-2"><h3 class="font-semibold">Technical responses</h3><article v-for="row in eligibilityReview.technical" :key="row.uuid" class="rounded-lg border border-base-200 p-3"><p class="text-xs text-base-content/45">{{ [row.group, row.lot, row.product].filter(Boolean).join(' · ') }}</p><p class="mt-1 text-sm font-medium">{{ row.question }}</p><div class="mt-2 flex items-center justify-between gap-2"><span class="badge" :class="row.file && !row.answer ? 'badge-info' : 'badge-outline'">{{ displayResponse(row) }}</span><button v-if="row.file" class="btn btn-outline btn-xs" @click="activeDocument = row.file">View attachment</button></div></article><p v-if="!eligibilityReview.technical.length" class="text-sm text-base-content/45">No technical questions configured.</p></section>
              <section class="mt-6 space-y-2"><h3 class="font-semibold">Specification compliance</h3><article v-for="row in eligibilityReview.specifications" :key="row.uuid" class="rounded-lg border border-base-200 p-3"><p class="text-xs text-base-content/45">{{ row.lot }} · {{ row.product }}</p><div class="mt-1 flex justify-between gap-3"><p class="text-sm font-medium">{{ row.specification }}: {{ row.required_value }}</p><span class="badge" :class="row.status === 'COMPLIANT' ? 'badge-success' : 'badge-warning'">{{ displayAnswer(row.status) }}</span></div><p v-if="row.offered_value || row.manufacturer_model || row.explanation" class="mt-2 text-xs text-base-content/60">Offered: {{ row.offered_value || '—' }} <span v-if="row.manufacturer_model">· {{ row.manufacturer_model }}</span> <span v-if="row.explanation">· {{ row.explanation }}</span></p><button v-if="row.file" class="btn btn-outline btn-xs mt-2" @click="activeDocument = row.file">View supporting document</button></article></section>
            </template>
            <section class="mt-6 space-y-3"><div><h3 class="font-semibold">Document evaluation</h3><p class="text-xs text-base-content/50">Inspect and assess every document attached to this bidder response.</p></div><article v-for="doc in documents" :key="doc.uuid" class="rounded-xl border p-3" :class="documentDecision(doc.uuid)?.compliant === false ? 'border-error/40 bg-error/5' : documentDecision(doc.uuid)?.compliant === true ? 'border-success/30 bg-success/5' : 'border-base-200'"><div class="flex flex-wrap items-start justify-between gap-2"><button type="button" class="min-w-0 text-left" @click="activeDocument = doc"><p class="font-medium">{{ doc.title || doc.file_name }}</p><p class="mt-1 truncate text-xs text-base-content/45">{{ doc.file_name }}</p></button><button type="button" class="btn btn-outline btn-xs" @click="activeDocument = doc"><Icon name="lucide:eye" class="h-3.5 w-3.5" />View</button></div><template v-if="canEvaluateOpenDocuments"><div class="mt-3 flex flex-wrap gap-4"><label class="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" class="checkbox checkbox-success checkbox-sm" :checked="decisionForms[documentBid.uuid].documents[doc.uuid].compliant === true" @change="setDocumentCompliance(doc.uuid, true, $event.target.checked)">Compliant</label><label class="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" class="checkbox checkbox-error checkbox-sm" :checked="decisionForms[documentBid.uuid].documents[doc.uuid].compliant === false" @change="setDocumentCompliance(doc.uuid, false, $event.target.checked)">Non-compliant</label></div><textarea v-if="decisionForms[documentBid.uuid].documents[doc.uuid].compliant === false" v-model.trim="decisionForms[documentBid.uuid].documents[doc.uuid].comments" class="textarea textarea-bordered textarea-sm mt-3 min-h-16 w-full" placeholder="Reason this document is non-compliant" /></template><template v-else-if="documentDecision(doc.uuid)"><div class="mt-3"><span class="badge badge-sm" :class="documentDecision(doc.uuid).compliant ? 'badge-success' : 'badge-error'">{{ documentDecision(doc.uuid).compliant ? 'Compliant' : 'Non-compliant' }}</span><p v-if="documentDecision(doc.uuid).comments" class="mt-2 whitespace-pre-wrap text-xs text-base-content/60">{{ documentDecision(doc.uuid).comments }}</p></div></template></article><p v-if="!documents.length" class="text-sm text-base-content/45">No attached documents require assessment.</p></section>
          </div>
          <div class="min-h-0 bg-base-200/40 p-3"><img v-if="activeDocument?.mime_type?.startsWith('image/')" :src="activeDocument.url" class="mx-auto max-h-full max-w-full object-contain" :alt="activeDocument.title"><iframe v-else-if="activeDocument" :src="activeDocument.url" class="h-full w-full rounded-lg bg-white" :title="activeDocument.title || activeDocument.file_name" /><div v-else class="flex h-full items-center justify-center text-base-content/40">Select an attachment to view it.</div></div>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop"><button @click="closeDocuments">close</button></form>
    </dialog>
  </div>
</template>

<script setup>
import LcsChairShortlist from '~/components/LcsChairShortlist.vue'
import LcsCommentsThread from '~/components/LcsCommentsThread.vue'
import LcsFinancialReview from '~/components/LcsFinancialReview.vue'
import { useLeastCostSelectionApi } from '~/features/least-cost-selection/api'

definePageMeta({ layout: 'default', sanctum: { authOnly: true } })
useHead({ title: 'LCS Evaluation Workspace' })
const route = useRoute(); const tenderUuid = String(route.params.uuid)
const api = useLeastCostSelectionApi()
const { transitionTender, getMyEvaluation } = useTenderHelper()
const { canEdit, canReview } = useCheckPermission('tenders')
const loading = ref(true); const saving = ref(false); const notInitialized = ref(false); const errorMessage = ref(''); const message = ref(''); const messageOk = ref(false)
const workspace = ref(null); const decisionForms = reactive({}); const pmuComments = ref(''); const aoComments = ref('')
const showShortlist = ref(false)
const draftsReady = ref(false); const hasLocalDrafts = ref(false)
const documentDialog = ref(null); const documents = ref([]); const activeDocument = ref(null); const documentBid = ref(null); const reviewMode = ref('eligibility'); const eligibilityReview = ref({ scope: null, eligibility: [], technical: [], specifications: [] })
const viewingCommittedDecision = ref(null)
const committeeEvaluationDialog = ref(null); const committeeEvaluations = ref([]); const committeeEvaluationsLoading = ref(false)
const evaluation = computed(() => workspace.value?.evaluation ?? null)
const canViewCommitteeEvaluations = computed(() => Boolean(workspace.value) && !['COMMITTEE_SETUP', 'COMMITTEE_APPOINTED', 'INDIVIDUAL_EVALUATION'].includes(evaluation.value?.status) && (workspace.value.actors.is_chairperson || workspace.value.actors.is_pmu_member || workspace.value.actors.is_accounting_officer))
const draftStorageKey = computed(() => `lcs-evaluation-draft:${tenderUuid}:${workspace.value?.actors?.user_uuid || 'unknown'}`)
const completedDraftCount = computed(() => (workspace.value?.bids ?? []).filter((bid) => {
  const decision = decisionForms[bid.uuid]
  return decision?.documents_reviewed && Object.values(decision.documents || {}).every(document => typeof document.compliant === 'boolean') && typeof decision?.compliant === 'boolean'
}).length)
const allDecisionsComplete = computed(() => (workspace.value?.bids?.length ?? 0) > 0 && (workspace.value?.bids ?? []).every((bid) => {
  const decision = decisionForms[bid.uuid]
  const documentsComplete = decision?.documents_reviewed && Object.values(decision.documents || {}).every(document => typeof document.compliant === 'boolean' && (document.compliant || Boolean(document.comments?.trim())))
  return documentsComplete && typeof decision?.compliant === 'boolean' && (decision.compliant || Boolean(decision.comments?.trim()) || Object.values(decision.documents || {}).some(document => document.compliant === false))
}))
const canEvaluateOpenDocuments = computed(() => reviewMode.value === 'eligibility' && !viewingCommittedDecision.value && workspace.value?.actors?.is_voting_member && ['INDIVIDUAL_EVALUATION', 'CHAIR_REVIEW'].includes(evaluation.value?.status) && Boolean(documentBid.value?.uuid && decisionForms[documentBid.value.uuid]))
const order = ['COMMITTEE_SETUP', 'COMMITTEE_APPOINTED', 'INDIVIDUAL_EVALUATION', 'CHAIR_REVIEW', 'PMU_REVIEW', 'ACCOUNTING_OFFICER_REVIEW', 'SPOC_FEE_PENDING', 'SPOC_REVIEW', 'APPROVED']
const displayedStageStatus = computed(() => {
  if (evaluation.value?.status === 'CHAIR_REVIEW' && !showShortlist.value) return 'INDIVIDUAL_EVALUATION'
  if (evaluation.value?.status === 'SPOC_FEE_PENDING') return 'SPOC_REVIEW'
  return evaluation.value?.status
})
const requiresSpoc = computed(() => workspace.value?.decision_route?.requires_spoc !== undefined
  ? Boolean(workspace.value.decision_route.requires_spoc)
  : Boolean(evaluation.value?.spoc_required_at_preparation || evaluation.value?.spoc_required_after_evaluation))
const stages = computed(() => {
  const route = [
    { key: 'COMMITTEE_SETUP', label: 'Committee' },
    { key: 'INDIVIDUAL_EVALUATION', label: 'Compliance' },
    { key: 'CHAIR_REVIEW', label: 'Shortlist' },
    { key: 'PMU_REVIEW', label: 'PMU' },
    { key: 'ACCOUNTING_OFFICER_REVIEW', label: 'Accounting Officer' },
  ]
  if (requiresSpoc.value) route.push({ key: 'SPOC_REVIEW', label: 'SPOC' })
  route.push({ key: 'APPROVED', label: 'Award' })
  return route.map(stage => ({ ...stage, done: order.indexOf(displayedStageStatus.value) >= order.indexOf(stage.key) }))
})
const humanize = value => String(value || '').replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase())
const formatDate = value => value ? new Date(value).toLocaleDateString('en-ZW', { dateStyle: 'medium' }) : '—'
const formatDateTime = value => value ? new Date(value).toLocaleString('en-ZW', { dateStyle: 'medium', timeStyle: 'short' }) : '—'
function readLocalDraft() { try { const raw = window.localStorage.getItem(draftStorageKey.value); return raw ? JSON.parse(raw) : null } catch { return null } }
function persistLocalDraft() { if (!draftsReady.value || !workspace.value?.actors?.is_voting_member) return; try { window.localStorage.setItem(draftStorageKey.value, JSON.stringify({ version: 1, tender_uuid: tenderUuid, saved_at: new Date().toISOString(), decisions: JSON.parse(JSON.stringify(decisionForms)) })); hasLocalDrafts.value = true } catch { hasLocalDrafts.value = true } }
function clearLocalDraft() { try { window.localStorage.removeItem(draftStorageKey.value) } catch { /* The committed server copy remains authoritative. */ } hasLocalDrafts.value = false }
async function hydrateForms() { draftsReady.value = false; Object.keys(decisionForms).forEach(key => delete decisionForms[key]); for (const bid of workspace.value?.bids ?? []) { const savedDocuments = Object.fromEntries((bid.my_decision?.document_decisions || []).map(document => [document.document_uuid, { compliant: document.compliant, comments: document.comments || '' }])); decisionForms[bid.uuid] = { compliant: bid.my_decision?.compliant ?? null, comments: bid.my_decision?.comments ?? '', documents: savedDocuments, documents_reviewed: bid.document_count === 0 || Object.keys(savedDocuments).length === bid.document_count } } const localDraft = workspace.value?.actors?.is_voting_member ? readLocalDraft() : null; for (const bid of workspace.value?.bids ?? []) { if (localDraft?.decisions?.[bid.uuid]) decisionForms[bid.uuid] = { ...decisionForms[bid.uuid], ...localDraft.decisions[bid.uuid], documents: { ...decisionForms[bid.uuid].documents, ...(localDraft.decisions[bid.uuid].documents || {}) } } } hasLocalDrafts.value = Boolean(localDraft?.decisions && Object.keys(localDraft.decisions).length); await nextTick(); draftsReady.value = true }
async function load() { loading.value = true; errorMessage.value = ''; const result = await api.workspace(tenderUuid); if (result.ok) { workspace.value = result.data; notInitialized.value = false; await hydrateForms() } else if (result.statusCode === 404) { const assigned = await getMyEvaluation(tenderUuid); if (assigned.status.value && assigned.data.value?.data?.evaluation_type === 'RFQ') { await navigateTo(`/evaluations/${tenderUuid}`, { replace: true }); return } notInitialized.value = true; errorMessage.value = result.error } else { errorMessage.value = result.error } loading.value = false }
async function run(action, success) { saving.value = true; message.value = ''; const result = await action(); messageOk.value = result.ok; message.value = result.ok ? success : result.error; if (result.ok) await load(); saving.value = false; return result }
async function startEvaluation() { saving.value = true; message.value = ''; const result = await transitionTender(tenderUuid, 'start_evaluation'); messageOk.value = result.status.value; message.value = result.status.value ? 'Evaluation started. Committee members can now assess bidder responses.' : result.error.value?.data?.message || result.error.value?.response?._data?.message || 'The evaluation could not be started.'; if (result.status.value) await load(); saving.value = false }
async function commitEvaluation() { if (!allDecisionsComplete.value) return; saving.value = true; message.value = ''; const decisions = workspace.value.bids.map(bid => ({ bid_uuid: bid.uuid, compliant: decisionForms[bid.uuid].compliant, comments: decisionForms[bid.uuid].comments || null, documents: Object.entries(decisionForms[bid.uuid].documents || {}).map(([document_uuid, decision]) => ({ document_uuid, compliant: decision.compliant, comments: decision.comments || null })) })); const result = await api.saveDecisions(tenderUuid, { decisions }); messageOk.value = result.ok; message.value = result.ok ? 'Evaluation decisions and document findings committed successfully.' : `${result.error} Your local draft has been retained.`; if (result.ok) { clearLocalDraft(); await load() } saving.value = false }
function openShortlist() { showShortlist.value = true; window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function handleShortlistSubmitted() { showShortlist.value = false; messageOk.value = true; message.value = 'Recommendation ranked and sent to the PMU.'; await load() }
const submitPmu = () => run(() => api.pmuSubmit(tenderUuid, { comments: pmuComments.value }), 'Recommendation sent to the Accounting Officer.')
const returnToChair = () => run(() => api.pmuReturnToChair(tenderUuid, { comments: pmuComments.value }), 'Recommendation returned to the chairperson.')
const submitAo = action => run(() => api.accountingOfficerDecision(tenderUuid, { action, comments: aoComments.value || null }), action === 'APPROVE' ? 'Award recommendation approved.' : 'Recommendation submitted for SPOC review.')
const returnToPmu = () => run(() => api.accountingOfficerReturnToPmu(tenderUuid, { comments: aoComments.value }), 'Recommendation returned to the PMU.')
const displayAnswer = value => value === null || value === undefined || value === '' ? 'Not answered' : String(value).replaceAll('_', ' ')
const displayResponse = row => row?.answer !== null && row?.answer !== undefined && row?.answer !== '' ? displayAnswer(row.answer) : row?.file ? 'Attachment provided' : 'Not answered'
async function openEligibility(bid, committedDecision = null) { reviewMode.value = 'eligibility'; viewingCommittedDecision.value = committedDecision; documentBid.value = bid; documents.value = []; eligibilityReview.value = { scope: null, eligibility: [], technical: [], specifications: [] }; activeDocument.value = null; documentDialog.value?.showModal(); const result = await api.documents(tenderUuid, bid.uuid); if (result.ok) { eligibilityReview.value = result.data; documents.value = result.data?.documents ?? []; if (!committedDecision && decisionForms[bid.uuid]) { for (const document of documents.value) decisionForms[bid.uuid].documents[document.uuid] ||= { compliant: null, comments: '' }; decisionForms[bid.uuid].documents_reviewed = true } } else { messageOk.value = false; message.value = result.error } }
async function openCommitteeEvaluations() { committeeEvaluationsLoading.value = true; committeeEvaluations.value = []; committeeEvaluationDialog.value?.showModal(); const result = await api.chairResponses(tenderUuid); if (result.ok) committeeEvaluations.value = result.data ?? []; else { messageOk.value = false; message.value = result.error; committeeEvaluationDialog.value?.close() } committeeEvaluationsLoading.value = false }
function openEvaluationEligibility(response) { committeeEvaluationDialog.value?.close(); openEligibility({ uuid: response.bid_uuid, bidder: response.bidder }, response) }
function openMinutes() { reviewMode.value = 'minutes'; documentBid.value = { bidder: { name: 'Evaluation committee' } }; eligibilityReview.value = { scope: null, eligibility: [], technical: [], specifications: [] }; documents.value = [{ uuid: 'minutes', title: 'Evaluation committee minutes', file_name: workspace.value.minutes?.filename || 'Committee minutes', mime_type: workspace.value.minutes?.mime_type || 'application/pdf', url: workspace.value.minutes_url }]; activeDocument.value = documents.value[0]; documentDialog.value?.showModal() }
function documentDecision(documentUuid) { if (canEvaluateOpenDocuments.value) return decisionForms[documentBid.value.uuid]?.documents?.[documentUuid] || null; return (viewingCommittedDecision.value?.document_decisions || []).find(decision => decision.document_uuid === documentUuid) || null }
function setDocumentCompliance(documentUuid, value, checked) { const decision = decisionForms[documentBid.value?.uuid]?.documents?.[documentUuid]; if (!decision) return; decision.compliant = checked ? value : decision.compliant === value ? null : decision.compliant; if (decision.compliant !== false) decision.comments = '' }
function closeDocuments() { documentDialog.value?.close(); activeDocument.value = null; documents.value = []; viewingCommittedDecision.value = null; eligibilityReview.value = { scope: null, eligibility: [], technical: [], specifications: [] } }
function warnBeforeUnload(event) { if (!hasLocalDrafts.value) return; event.preventDefault(); event.returnValue = '' }
watch(decisionForms, () => { for (const decision of Object.values(decisionForms)) { if (Object.values(decision.documents || {}).some(document => document.compliant === false)) decision.compliant = false } persistLocalDraft() }, { deep: true })
onMounted(() => { window.addEventListener('beforeunload', warnBeforeUnload); load() })
onBeforeUnmount(() => window.removeEventListener('beforeunload', warnBeforeUnload))
</script>
